In [13]:
# Vectorization
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [14]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("Vectorization time: " + str(1000*(toc - tic)) + "ms")

250280.05234593703
Vectorization time: 1.3968944549560547ms


In [15]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()
print(c)
print("For loop time: " + str(1000*(toc - tic)) + "ms")

250280.05234595007
For loop time: 750.3054141998291ms


In [1]:
# Vectorizing logistic regression
z = np.dot(w.T, x) + b


# Vectorizing Logistic Regression's Gradient Output
dz = 1 / m * np.sum(z)


In [ ]:
# One of Example with numpy
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

In [ ]:
cel = A.sum(axis = 0)
print(cel)

percentages = 100 * A / cel.reshape(1, 4)
print(percentages)

Helpful NumPy hint 

In [ ]:
c = np.random.rand(5)
print(c)

In [ ]:
print(c.T)

In [ ]:
print(np.dot(c, c.T))

In [17]:
c = np.random.rand(5, 1)
print(c)
print(c.T)

[[0.22001695]
 [0.2669924 ]
 [0.84168832]
 [0.91176887]
 [0.45923848]]
[[0.22001695 0.2669924  0.84168832 0.91176887 0.45923848]]


In [18]:
print(np.dot(c, c.T))

[[0.04840746 0.05874285 0.18518569 0.2006046  0.10104025]
 [0.05874285 0.07128494 0.22472439 0.24343536 0.12261319]
 [0.18518569 0.22472439 0.70843922 0.7674252  0.38653567]
 [0.2006046  0.24343536 0.7674252  0.83132247 0.41871935]
 [0.10104025 0.12261319 0.38653567 0.41871935 0.21089998]]
