In [1]:
# Vectorization
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("Vectorization time: " + str(1000*(toc - tic)) + "ms")

In [ ]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()
print(c)
print("For loop time: " + str(1000*(toc - tic)) + "ms")

In [ ]:
# Vectorizing logistic regression
z = np.dot(w.T, x) + b


# Vectorizing Logistic Regression's Gradient Output
dz = 1 / m * np.sum(z)


In [2]:
# One of Example with numpy
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cel = A.sum(axis = 0)
print(cel)

percentages = 100 * A / cel.reshape(1, 4)
print(percentages)

[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


Helpful NumPy hint 

In [8]:
c = np.random.rand(5)
print(c)

[0.06242331 0.06163379 0.70338063 0.64858068 0.54162099]


In [9]:
print(c.T)

[0.06242331 0.06163379 0.70338063 0.64858068 0.54162099]


In [10]:
print(np.dot(c, c.T))

1.2164499071071768


In [11]:
c = np.random.rand(5, 1)
print(c)
print(c.T)

[[0.65382837]
 [0.63876443]
 [0.9297754 ]
 [0.87040457]
 [0.36661821]]
[[0.65382837 0.63876443 0.9297754  0.87040457 0.36661821]]


In [12]:
print(np.dot(c, c.T))

[[0.42749154 0.4176423  0.60791354 0.5690952  0.23970539]
 [0.4176423  0.40802    0.59390746 0.55598348 0.23418267]
 [0.60791354 0.59390746 0.8644823  0.80928076 0.3408726 ]
 [0.5690952  0.55598348 0.80928076 0.75760411 0.31910617]
 [0.23970539 0.23418267 0.3408726  0.31910617 0.13440891]]
