In [13]:
# Vectorization
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [14]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("Vectorization time: " + str(1000*(toc - tic)) + "ms")

250280.05234593703
Vectorization time: 1.3968944549560547ms


In [15]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()
print(c)
print("For loop time: " + str(1000*(toc - tic)) + "ms")

250280.05234595007
For loop time: 750.3054141998291ms


In [1]:
# Vectorizing logistic regression
z = np.dot(w.T, x) + b


# Vectorizing Logistic Regression's Gradient Output
dz = 1 / m * np.sum(z)


In [2]:
# One of Example with numpy
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cel = A.sum(axis = 0)
print(cel)

percentages = 100 * A / cel.reshape(1, 4)
print(percentages)

[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


Helpful NumPy hint 

In [4]:
c = np.random.rand(5)
print(c)

[0.12961075 0.95557895 0.51322022 0.24392085 0.14653367]


In [5]:
print(c.T)

[0.12961075 0.95557895 0.51322022 0.24392085 0.14653367]


In [6]:
print(np.dot(c, c.T))

1.2742945677218076


In [7]:
c = np.random.rand(5, 1)
print(c)
print(c.T)

[[0.16381293]
 [0.86297348]
 [0.58394475]
 [0.78715174]
 [0.07364398]]
[[0.16381293 0.86297348 0.58394475 0.78715174 0.07364398]]


In [8]:
print(np.dot(c, c.T))

[[0.02683468 0.14136622 0.0956577  0.12894563 0.01206384]
 [0.14136622 0.74472323 0.50392883 0.67929108 0.06355281]
 [0.0956577  0.50392883 0.34099147 0.45965313 0.04300402]
 [0.12894563 0.67929108 0.45965313 0.61960786 0.05796899]
 [0.01206384 0.06355281 0.04300402 0.05796899 0.00542344]]
